### ISSUE TITLE
1.0 ideas and tracking

### ISSUE THREAD

**Issue by bugadani** [bugadani/Slots#9]
Use this issue to collect issues, ideas towards a 1.0 release.

Current open topics:
- Naming. The inclusion of SlotMap will make the Slots name even less descriptive and useful.

To Do:
- [ ] Fixed size SlotMap implementation based on [this talk](https://www.youtube.com/watch?v=-8UZhDjgeZU)
- [x] Optimize the next_free member (#13)
- [x] Iterator support (Relaxed may have mutable)
- [x] Less cluttered API (#12)
- [x] Option for a more relaxed access mode (~#10 or #11~ #17)
- [x] Documentation improvements
